<?php

declare(strict_types=1);

/**
 * @file
 * Provides a substitutoo scheduler assignment entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function sub_scheduler_assignment_theme(): array {
  return [
    'sub_scheduler_assignment' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for substitutoo scheduler assignment templates.
 *
 * Default template: sub-scheduler-assignment.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the substitutoo scheduler assignment information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_sub_scheduler_assignment(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function sub_scheduler_assignment_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish substitutoo scheduler assignments.
      $storage = \Drupal::entityTypeManager()->getStorage('sub_scheduler_assignment');
      $sub_scheduler_assignment_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($sub_scheduler_assignment_ids) as $sub_scheduler_assignment) {
        $sub_scheduler_assignment->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize substitutoo scheduler assignments.
      $storage = \Drupal::entityTypeManager()->getStorage('sub_scheduler_assignment');
      $sub_scheduler_assignment_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($sub_scheduler_assignment_ids) as $sub_scheduler_assignment) {
        $sub_scheduler_assignment->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function sub_scheduler_assignment_user_predelete(UserInterface $account): void {
  // Delete substitutoo scheduler assignments that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('sub_scheduler_assignment');
  $sub_scheduler_assignment_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($sub_scheduler_assignment_ids)
  );
}
