<?php

declare(strict_types=1);

/**
 * @file
 * Provides a substitutoo availability entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function sub_availability_theme(): array {
  return [
    'sub_availability' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for substitutoo availability templates.
 *
 * Default template: sub-availability.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the substitutoo availability information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_sub_availability(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function sub_availability_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish substitutoo availabilities.
      $storage = \Drupal::entityTypeManager()->getStorage('sub_availability');
      $sub_availability_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($sub_availability_ids) as $sub_availability) {
        $sub_availability->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize substitutoo availabilities.
      $storage = \Drupal::entityTypeManager()->getStorage('sub_availability');
      $sub_availability_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($sub_availability_ids) as $sub_availability) {
        $sub_availability->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function sub_availability_user_predelete(UserInterface $account): void {
  // Delete substitutoo availabilities that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('sub_availability');
  $sub_availability_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($sub_availability_ids)
  );
}
