<?php

declare(strict_types=1);

/**
 * @file
 * Provides a substitutoo assignment history entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function sub_assignment_history_theme(): array {
  return [
    'sub_assignment_history' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for substitutoo assignment history templates.
 *
 * Default template: sub-assignment-history.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the substitutoo assignment history information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_sub_assignment_history(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function sub_assignment_history_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish substitutoo assignment histories.
      $storage = \Drupal::entityTypeManager()->getStorage('sub_assignment_history');
      $sub_assignment_history_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($sub_assignment_history_ids) as $sub_assignment_history) {
        $sub_assignment_history->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize substitutoo assignment histories.
      $storage = \Drupal::entityTypeManager()->getStorage('sub_assignment_history');
      $sub_assignment_history_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($sub_assignment_history_ids) as $sub_assignment_history) {
        $sub_assignment_history->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function sub_assignment_history_user_predelete(UserInterface $account): void {
  // Delete substitutoo assignment histories that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('sub_assignment_history');
  $sub_assignment_history_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($sub_assignment_history_ids)
  );
}
