sub_ai.settings:
  type: config_object
  label: 'Ai Customer Support settings'
  mapping:
    api_url:
      type: string
      label: 'OpenAI API base url'
    api_key:
      type: string
      label: 'OpenAI API key'
    api_org:
      type: string
      label: 'OpenAI organization ID'
    fine_tuning_id:
      type: string
      label: 'OpenAI fine tunning ID'
    model_id:
      type: string
      label: 'OpenAI model ID'
