<?php

declare(strict_types=1);

/**
 * @file
 * Provides an ai customer support entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function sub_ai_theme(): array {
  return [
    'sub_ai' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for ai customer support templates.
 *
 * Default template: ai-customer-support.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the ai customer support information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_sub_ai(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function sub_ai_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish ai customer supports.
      $storage = \Drupal::entityTypeManager()->getStorage('sub_ai');
      $sub_ai_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($sub_ai_ids) as $sub_ai) {
        $sub_ai->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize ai customer supports.
      $storage = \Drupal::entityTypeManager()->getStorage('sub_ai');
      $sub_ai_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($sub_ai_ids) as $sub_ai) {
        $sub_ai->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function sub_ai_user_predelete(UserInterface $account): void {
  // Delete ai customer supports that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('sub_ai');
  $sub_ai_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($sub_ai_ids)
  );
}
